name = "blt-ossh"
main = "src/main.py"
compatibility_date = "2025-11-02"
compatibility_flags = ["python_workers"]


# Static assets configuration
[assets]
directory = "./static"

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[observability]
enabled = true
